library(nws)
library(grid)
options(device='X11')
grid.newpage()
host <- Sys.getenv('PF_HOST', 'localhost')
port <- as.integer(Sys.getenv('PF_PORT', '8765'))
si <- serverInfo(host=host, port=port)
ws <- suppressWarnings(netWorkSpace(Sys.getenv('PF_WORKSPACE'), serverInfo=si))
nwsStore(ws, 'par', 'ready')
ignore <- nwsFind(ws, 'go')
source('pportfolio.R')
ignore <- grid.locator()
